<a href="https://colab.research.google.com/github/manola1109/Introduction-to-PyTorch/blob/main/4_2_PyTorch_Autograd_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing torch library
import torch

In [2]:
# initializing a 2d tensor
a = torch.tensor([[1,1], [1,1]], dtype=torch.float)
a

tensor([[1., 1.],
        [1., 1.]])

In [3]:
# performing operations on the tensor
b = a + 5
print(b)

tensor([[6., 6.],
        [6., 6.]])


In [4]:
# performing another operation
c = b.mean()
print(c)

tensor(6.)


### Operations we have applied



1. First of all, we added 5 to all the elements of this tensor
2. Then, we took the mean of that tensor

We performed the following operations on a:

b = a + 5

c = mean(b) = Σ(a+5) / 4






### Gradient of c with respect to a

dc / da = dc/db * db / da = 1/4(1+0) * (1+0) = 1/4 = 0.25

Similarly, we can compute for all elements of a

## Automatic Differentiation

In [5]:
# initializing a 2d tensor and setting requires_grad as True
a = torch.tensor([[1,1], [1,1]], dtype= torch.float, requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [6]:
# performing operations on the tensor
b = a + 5
c = b.mean()
print(b)
print(c)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)
tensor(6., grad_fn=<MeanBackward0>)


In [7]:
# back propagating
c.backward()

In [8]:
# calculated gradients
print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
